import os
import json
import subprocess
import argparse
import numpy as np
from tqdm import tqdm

# EXACT prompt from evaluation_struct.py
EVAL_CHANGE_PROMPT = """<Role>
You are an objective Evaluation Assistant specialized in analyzing code review predictions against ground truth information.
</Role>

<OverallTask>
Your task is to evaluate a predicted code review based on how accurately it identifies the actual **changes or issues** present in a pull request (PR). You will compare the points raised in the predicted review against a ground truth list of confirmed changes/issues introduced by the PR.
</OverallTask>

<InputContext>
    <PullRequestDetails>
        <Note>This PR is known to contain the changes/issues listed in GroundTruthChanges.</Note>
        <Title>{pr_title}</Title>
        <Description>{pr_statement}</Description>
        <GroundTruthReviewContent>
        {ground_truth_reviews}
        </GroundTruthReviewContent>
    </PullRequestDetails>

    <GroundTruthChanges>
        <Description>This section lists the actual changes/issues confirmed to be present in the pull request. Each item has an ID, a change category, and a description.</Description>
        <Content>
{changes_description}
        </Content>
    </GroundTruthChanges>

    <PredictedReview>
        <Content>
{pred_review}
        </Content>
        <Note>This is the review generated by the system being evaluated.</Note>
    </PredictedReview>
</InputContext>

<ReferenceData>
    <ChangeCategoryDefinitions>
        <Description>Use these categories to classify any points identified in the <PredictedReview> and to understand the categories provided in <GroundTruthChanges>.</Description>
        <Categories>
        - **E. Evolvability Changes**: Modifications improving code readability, maintainability, or overall structure without altering core functionality.
            - **E.1 Documentation**: Enhancements to code comprehension for developers through documentation elements.
                - *E.1.1 Textual Changes*: Adjustments to comments (e.g., adding, correcting, clarifying) or identifier names (variables, functions, classes) for better clarity and consistency.
                - *E.1.2 Language Features*: Utilizing language-specific constructs (e.g., `final` in Java, type annotations, access modifiers) primarily to convey developer intent, constraints, or information, rather than for functional impact.
            - **E.2 Visual Representation**: Modifications to code formatting and layout, such as indentation, spacing, line breaks, or bracket placement, to improve visual clarity and adhere to style conventions.
            - **E.3 Structure**: Changes affecting the organization or implementation strategy of the code without changing its external behavior.
                - *E.3.1 Organization*: Reorganizing code elements, such as removing dead (unused) code, moving functions or classes to more appropriate locations, or restructuring files/packages for better modularity.
                - *E.3.2 Solution Approach*: Modifying the internal implementation details or algorithms (e.g., refactoring for clarity/efficiency, updating function usage to newer patterns), or adding supporting code like tests, without altering the observable functionality.

        - **F. Functional Changes**: Corrections addressing errors in the code's behavior, output, or interaction with other system parts.
            - **F.1 Interface**: Fixes related to how different code components interact, including incorrect method calls, wrong parameter types/values, violated API contracts, or incorrect event handling.
            - **F.2 Logic**: Corrections to errors in algorithms, conditional statements (if/else), loops, computations, or other logical constructs leading to incorrect behavior.
            - **F.3 Resource**: Fixes concerning the management of data, variables, or system resources, including initialization errors, memory leaks, improper resource release/acquisition, or incorrect data manipulation (e.g., concurrency issues).
            - **F.4 Check**: Adding or modifying validation or checks (e.g., null checks, boundary checks, state validation) for variables, parameters, or function return values to handle potential errors or invalid states correctly.
            - **F.5 Support**: Corrections related to the interaction with external systems, libraries, frameworks, or APIs (e.g., incorrect usage, adapting to API changes, version incompatibilities).
            - **F.6 Larger Defects**: Significant functional fixes that often span multiple files or components, address incompletely implemented and feature, fix major inconsistencies (like GUI behavior), or require broader system knowledge. These might not always be fully resolved within the same PR.
        </Categories>
    </ChangeCategoryDefinitions>

    <SeverityScale>
        <Description>Use this scale to evaluate the inherent severity of the points identified in the <PredictedReview>.</Description>
        <Scale>
            *   **1-2: Trivial** (e.g., minor comment typo, inconsequential whitespace change suggestion).
            *   **3-4: Minor** (e.g., suggestion for slightly inefficient code, unclear logging message, minor style deviation).
            *   **5-6: Moderate** (e.g., identifying a specific edge case error, a noticeable performance issue suggestion).
            *   **7-8: Major** (e.g., identifying incorrect logic, a crash in a non-core function).
            *   **9-10: Critical** (e.g., identifying a core functionality crash, a security vulnerability).
        </Scale>
    </SeverityScale>
</ReferenceData>

<EvaluationInstructions>
Follow these steps precisely:

1.  **Analyze Predicted Review Content:**
    *   Carefully read the content within `<InputContext><PredictedReview><Content>`.
    *   Determine if the review **explicitly states or strongly implies** the PR is clean, good, approved, or ready to merge (e.g., using phrases like 'LGTM', 'Approved', 'Looks good', 'No issues found').
    *   Record this determination as `YES` or `NO` for the `identified_as_good` field in the output. **Base this assessment solely on such explicit statements, even if minor suggestions are also present.**

2.  **Identify and Analyze Predicted Points:**
    *   Carefully read the content within `<InputContext><PredictedReview><Content>`.
    *   Identify *each distinct suggestion, issue, potential defect, or point for change* mentioned in the review.
    *   For each identified point:
        *   Assign a unique sequential ID: `PRED-POINT-1`, `PRED-POINT-2`, etc.
        *   Extract the core original description of the point directly from the `<InputContext><PredictedReview><Content>`.
        *   Determine the most appropriate change category for the point by referencing the definitions in `<ReferenceData><ChangeCategoryDefinitions>`. Use the specific code (e.g., `E.1.1`, `F.2`).
        *   Evaluate the **inherent severity** of the *potential* issue raised by the point, based on its nature (independent of whether it matches a ground truth change). Use the scale provided in `<ReferenceData><SeverityScale>` (1-10).
        *   Record the ID, description, change category, and severity score for each identified point.

3.  **Match Ground Truth Changes to Predicted Points:**
    *   For *each* change listed in `<InputContext><GroundTruthChanges><Content>` (e.g., `GT-CHANGE-1`, `GT-CHANGE-2`, etc., assuming IDs are provided in the input):
        *   Review its description and change category.
        *   Determine if any of the predicted points identified in Step 1 (`PRED-POINT-1`, `PRED-POINT-2`, etc.) successfully **hit** this ground truth change. A hit occurs if a predicted point *substantially and correctly identifies the core essence* of the ground truth change based on their **semantic meaning and description**. The assigned severity or exact wording doesn't need to match perfectly.
        *   If multiple predicted points seem relevant to a single ground truth change, choose the predicted point that provides the *most accurate and complete semantic* description of the ground truth change as the primary hit. A ground truth change should only be marked as hit by *one* predicted point at most.
        *   Record `Hit: YES` or `Hit: NO` for the ground truth change.
        *   If `Hit: YES`, record the ID (e.g., `PRED-POINT-1`) of the specific predicted point that hit it in the `Hit by:` field.
        *   If `Hit: NO`, record `Hit by: N/A`.

</EvaluationInstructions>

<OutputFormat>
Provide your evaluation **strictly** in the following JSON format. Do not include any text outside the JSON structure. Ensure all ground truth changes from the input are listed in the `gt_changes` array, in the same order they appeared in the input.

```json
{{
  "identified_as_good": "[YES or NO]",
  "pred_points": [
    // Include one object for each distinct point identified in the Predicted Review (Step 1).
    // If no points were raised, return an empty array: []
    {{
      "id": "PRED-POINT-1",
      "description": "[Extract the original description of the first point from <InputContext><PredictedReview><Content>]",
      "change_category": "[Assign the category code (e.g., E.1.1, F.2) from <ReferenceData><ChangeCategoryDefinitions>]",
      "severity_score": "[Assign the score (1-10) based on <ReferenceData><SeverityScale>]"
    }},
    {{
      "id": "PRED-POINT-2",
      "description": "[Extract the original description of the second point from <InputContext><PredictedReview><Content>]",
      "change_category": "[Assign the category code (e.g., E.1.1, F.2) from <ReferenceData><ChangeCategoryDefinitions>]",
      "severity_score": "[Assign the score (1-10) based on <ReferenceData><SeverityScale>]"
    }}
    // ... continue for all identified predicted points ...
  ],
  "gt_points": [
    // Include one object for each ground truth change listed in <InputContext><GroundTruthChanges><Content>.
    // Maintain the original order from the input.
    {{
      "id": "[Copy ID from the corresponding Ground Truth Change input, e.g., GT-CHANGE-1]",
      "description": "[Copy description from the corresponding Ground Truth Change input]",
      "change_category": "[Copy category from the corresponding Ground Truth Change input]",
      "hit": "[YES or NO - Based on Step 2 analysis]",
      "hit_by": "[PRED-POINT-ID if Hit is YES, otherwise N/A]"
    }},
    {{
      "id": "[Copy ID from the corresponding Ground Truth Change input, e.g., GT-CHANGE-2]",
      "description": "[Copy description from the corresponding Ground Truth Change input]",
      "change_category": "[Copy category from the corresponding Ground Truth Change input]",
      "hit": "[YES or NO - Based on Step 2 analysis]",
      "hit_by": "[PRED-POINT-ID if Hit is YES, otherwise N/A]"
    }}
    // ... continue for all Ground Truth Changes listed in the input ...
  ]
}}
```
"""

def call_llm_judge(prompt, model="gemma4:31b"):
    # We use the 'claude' CLI as a proxy for calling the LLM
    # In a real scenario, this would be an API call.
    try:
        result = subprocess.run(
            ["claude", "--model", model, prompt],
            capture_output=True,
            text=True,
            check=True
        )
        output = result.stdout
        # Extract JSON from markdown code blocks if present
        if "```json" in output:
            output = output.split("```json")[1].split("```")[0]
        elif "```" in output:
            output = output.split("```")[1].split("```")[0]
        return json.loads(output.strip())
    except Exception as e:
        print(f"Error calling LLM judge: {e}")
        return None

def calculate_prf1(tp, fp, fn):
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    return round(precision, 4), round(recall, 4), round(f1, 4)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--gt-dir", type=str, required=True, help="Directory for ground truth dataset")
    parser.add_argument("--res-dir", type=str, required=True, help="Directory for produced results")
    parser.add_argument("--model", type=str, default="gemma4:31b", help="Model to use as judge")
    parser.add_argument("--output-file", type=str, default="evaluation_report.json", help="Output report file")
    args = parser.parse_args()

    # Load results and GT
    res_files = [f for f in os.listdir(args.res_dir) if f.endswith(".txt")]
    gt_dir = args.gt_dir

    all_results = []

    for res_file in tqdm(res_files, desc="Evaluating PRs"):
        pr_id = res_file.replace(".txt", "")
        gt_path = os.path.join(gt_dir, f"{pr_id}.json")

        if not os.path.exists(gt_path):
            continue

        with open(gt_path, 'r') as f:
            gt_data = json.load(f)

        with open(os.path.join(args.res_dir, res_file), 'r') as f:
            pred_review = f.read()

        # Construct ground truth changes description
        changes_description = []
        for i, change in enumerate(gt_data.get('changes', [])):
            comments = " ".join(change.get('review_comments', []))
            changes_description.append(
                f"        <Ground Truth Change GT-POINT-{i+1}>\n"
                f"            Change Category: E.1.1 Textual Changes\n"
                f"            Change Description: {comments}\n"
                f"            Change Code Snippet: File {change.get('path', 'unknown')}, line {change.get('line', 'unknown')}\n"
                f"        </Ground Truth Change GT-POINT-{i+1}>\n"
            )

        # Construct ground truth reviews
        reviews = []
        for c in gt_data.get('issue_context', {}).get('comments', []):
            reviews.append(f"<Start of Comment>\nComment: {c}\n<End of Comment>")
        for c in gt_data.get('pr_comments', []):
            reviews.append(f"<Start of Review Comment>\nComment: {c}\n<End of Review Comment>")

        prompt = EVAL_CHANGE_PROMPT.format(
            pr_title=gt_data.get('pr_title', 'N/A'),
            pr_statement=gt_data.get('pr_body', 'N/A'),
            changes_description="\n".join(changes_description),
            ground_truth_reviews="\n".join(reviews),
            pred_review=pred_review
        )

        eval_res = call_llm_judge(prompt, args.model)
        if eval_res:
            all_results.append({
                "pr_id": pr_id,
                "eval": eval_res
            })

    # Global Metrics
    tp_total = 0
    fp_total = 0
    fn_total = 0

    pr_details = []

    for item in all_results:
        res = item['eval']
        pred_points = res.get('pred_points', [])
        gt_points = res.get('gt_points', [])

        pred_point_ids = {p['id'] for p in pred_points}
        hit_by_ids = {g['hit_by'] for g in gt_points if g['hit'].upper() == 'YES'}

        tp = len(hit_by_ids)
        fp = len(pred_point_ids - hit_by_ids)
        fn = len(gt_points) - tp

        tp_total += tp
        fp_total += fp
        fn_total += fn

        pr_details.append({
            "pr_id": item['pr_id'],
            "tp": tp,
            "fp": fp,
            "fn": fn,
            "identified_as_good": res.get('identified_as_good')
        })

    precision, recall, f1 = calculate_prf1(tp_total, fp_total, fn_total)

    final_report = {
        "metrics": {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "tp_total": tp_total,
            "fp_total": fp_total,
            "fn_total": fn_total
        },
        "details": pr_details
    }

    with open(args.output_file, 'w') as f:
        json.dump(final_report, f, indent=4)

    print(f"\nEvaluation Complete.")
    print(f"Precision: {precision}, Recall: {recall}, F1: {f1}")
    print(f"TP: {tp_total}, FP: {fp_total}, FN: {fn_total}")
    print(f"Report saved to {args.output_file}")

if __name__ == "__main__":
    main()
